### ISSUE TITLE
[builtin package] Go v1.11.4 [LSP: Go compiler] illegal cycle in declaration of bool

### ISSUE THREAD

**Issue by chrisduong** [saibing/bingo#52]
I don't know I received this error recently from the _builtin_ package.

I'm using latest Bingo version at this moment. My VScode settings is

```yaml
    "go.languageServerExperimentalFeatures": {
        "format": true,
        "rename": true,
        "goToDefinition": true,
        "hover": true,
        "autoComplete": true,
        "signatureHelp": true,
        "goToTypeDefinition": true,
        "goToImplementation": true,
        "documentSymbols": true,
        "workspaceSymbols": true,
        "findReferences": true
    },
```

<img width="519" alt="image" src="https://user-images.githubusercontent.com/1848882/50888089-cdc88600-142f-11e9-83aa-6ef3f584bc0d.png">
